name: PR Summary Generator

on:
    workflow_dispatch:
  
    pull_request:
      branches:
        - main
  
    push:
      branches:
        - main

jobs:
  pr_summary:
    runs-on: ubuntu-latest
    name: PR Summarizer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Summarize PR with AI
        uses: behrouz-rad/ai-pr-summarizer@v1
        with:
          llm-model: 'gpt-3.5-turbo'
          prompt-file: .github/workflows/assets/prompt-file.txt
          models-file: .github/workflows/assets/models-file.txt
          version-file: .github/workflows/assets/version-file.txt
          context-window: 4096
          upload-changes: true
          fail-on-error: true
          token: ${{ secrets.GITHUB_TOKEN }}
