name: GPT Commits summarizer
# Summary: This action will write a comment about every commit in a pull request, as well as generate a summary for every file that was modified and add it to the review page, compile a PR summary from all commit summaries and file diff summaries, and delete outdated code review comments

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions: write-all  # Some repositories need this line

    steps:
      - uses: KanHarI/gpt-commit-summarizer@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
# name: PR Summary Generator

# on:
#     workflow_dispatch:
  
#     pull_request:
#       branches:
#         - main
  
#     push:
#       branches:
#         - main

# jobs:
#   pr_summary:
#     runs-on: ubuntu-latest
#     name: PR Summarizer
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Summarize PR with AI
#         uses: behrouz-rad/ai-pr-summarizer@v1
#         with:
#           llm-model: 'deepseek-coder-v2:latest'
#           prompt-file: .github/workflows/assets/prompt-file.txt
#           models-file: .github/workflows/assets/models-file.txt
#           version-file: .github/workflows/assets/version-file.txt
#           context-window: 4096
#           upload-changes: true
#           fail-on-error: true
#           token: ${{ secrets.GITHUB_TOKEN }}
