name: PR Summary Generator

on:
  pull_request:
    branches:
      - main

jobs:
  pr_summary:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          export PATH=$PATH:/usr/local/bin
          ollama serve &
          sleep 5

      - name: Pull Mistral Model
        run: ollama pull mistral

      - name: Verify Installed Models
        run: ollama list

      - name: Generate PR Summary
        id: pr_summary
        run: |
          # Get the list of changes (limited to first 1000 lines for safety)
          DIFF=$(git diff --unified=3 --color=never origin/main...HEAD | head -n 1000)

          if [[ -z "$DIFF" ]]; then
            echo "PR_SUMMARY=No significant changes detected." >> $GITHUB_ENV
          else
            # Generate a summary using the AI model
            RESPONSE=$(curl -s -X POST http://localhost:11434/api/generate \
              -H "Content-Type: application/json" \
              -d '{
                "model": "mistral",
                "prompt": "Generate a concise yet informative summary of the following pull request changes:\n\n'"$DIFF"'",
                "stream": false
              }')

            # Debug raw response
            echo "Raw Response: $RESPONSE"

            # Extract the response text
            SUMMARY=$(echo "$RESPONSE" | jq -r '.response // "Failed to generate summary"')
            echo "PR_SUMMARY=$SUMMARY" >> $GITHUB_ENV
          fi

      - name: Post PR Summary Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="### 🤖 AI-Generated PR Summary\n\n$PR_SUMMARY"
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          gh api repos/$REPO/issues/$PR_NUMBER/comments -f body="$COMMENT"
