name: PR Summary Generator

on:
  pull_request:
    branches:
      - main

jobs:
  pr_summary:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          export PATH=$PATH:/usr/local/bin
          ollama serve &
          sleep 5

      - name: Pull Mistral Model
        run: ollama pull mistral

      - name: Generate PR Summary
        id: pr_summary
        run: |
          # Get the list of changes
          DIFF=$(git diff --unified=3 --color=never origin/main...HEAD)

          # Generate a summary using the AI model
          RESPONSE=$(curl -s -X POST http://localhost:11434/api/generate \
            -H "Content-Type: application/json" \
            -d '{
              "model": "mistral",
              "prompt": "Generate a concise yet informative summary of the following changes in the pull request: '"$DIFF"'",
              "stream": false
            }')

          # Extract the response text
          SUMMARY=$(echo "$RESPONSE" | jq -r '.response')

          echo "PR_SUMMARY=$SUMMARY" >> $GITHUB_ENV

      - name: Post PR Summary Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="### 🤖 AI-Generated PR Summary\n\n$PR_SUMMARY"
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          gh api repos/$REPO/issues/$PR_NUMBER/comments -f body="$COMMENT"
